# Generated by Django 3.2.10 on 2021-12-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20211224_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
    ]
