# Generated by Django 4.0 on 2022-01-04 11:52

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0002_cartitem_product_cartitem_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sale_price',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name=products.models.Product),
        ),
    ]
