# Generated by Django 4.0 on 2022-01-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0002_user_provider_accounts_id_user_provider_type_code'),
        ('cart', '0003_alter_productcratitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCratItem',
            new_name='CratItem',
        ),
    ]
