# Generated by Django 4.0 on 2022-01-04 10:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='판매가격',
            field=models.PositiveIntegerField(default=1, verbose_name=products.models.Product),
            preserve_default=False,
        ),
    ]
