# Generated by Django 4.0 on 2022-01-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0002_user_provider_accounts_id_user_provider_type_code'),
        ('cart', '0004_rename_productcratitem_cratitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CratItem',
            new_name='CartItem',
        ),
    ]
