# Generated by Django 4.0 on 2021-12-31 10:13

from django.db import migrations, models

from products.models import ProductCategory


def gen_master(apps, schema_editor):
    ProductCategory(name='구두').save()
    ProductCategory(name='니트').save()
    ProductCategory(name='롱스커트').save()
    ProductCategory(name='스커트').save()
    ProductCategory(name='청바지').save()
    ProductCategory(name='청자켓').save()
    ProductCategory(name='청치마').save()
    ProductCategory(name='코트').save()
    ProductCategory(name='토드백').save()
    ProductCategory(name='블라우스').save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productreal_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SIZE', max_length=10, verbose_name='이름')),
            ],
        ),
        migrations.RunPython(gen_master),
    ]
